apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorio
  namespace: factorio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      initContainers:
      - name: copy-config
        image: busybox
        command:
          - sh
          - -c
          - |
            mkdir -p /tmp/config && \
            cp /secret/server-settings.json /tmp/config/server-settings.json && \
            chown -R 835:835 /tmp/config
        volumeMounts:
          - name: secret-config
            mountPath: /secret
          - name: config
            mountPath: /tmp/config
      containers:
      - name: factorio
        image: docker.io/factoriotools/factorio:stable
        ports:
          - name: game
            hostPort: 34197
            containerPort: 34197
            protocol: UDP
          - name: factorio-server
            containerPort: 27015
            protocol: TCP
        volumeMounts:
          - name: save-data
            mountPath: /factorio/
          - name: config
            mountPath: /factorio/config/server-settings.json
            subPath: server-settings.json
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: save-data
          persistentVolumeClaim:
            claimName: factorio-saves
        - name: secret-config
          secret:
            secretName: factorio-settings
        - name: config
          emptyDir: {}
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
