apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- minecraft-deployment.yaml
- minecraft-service.yaml
- minecraft-service-ext.yaml
- minecraft-pvc.yaml
- minecraft-namespace.yaml
- minecraft-ingress.yaml
- minecraft-service-metrics.yaml
