apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minecraft-web
  namespace: minecraft
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: "nginx"
  rules:
  - host: "minecraft.marsellihome.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minecraft-service
            port:
              name: web-map
  tls:
  - hosts:
    - "minecraft.marsellihome.com"
    secretName: minecraft-web-tls
